name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Apt dependencies
      run: sudo apt-get install -y texlive-xetex
    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
        sudo dpkg -i pandoc-2.14.1-1-amd64.deb
    - name: Install Pip dependencies
      run: python -m pip install -r requirements.dev.txt
    - name: Test
      run: coverage run -m unittest -v
    - name: Codecov
      run: codecov
